//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// Copyright (C) 2020 - 2023 by the ryujin authors
//

#pragma once

#include "geometry_common_includes.h"

#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_tools.h>

namespace ryujin
{

  namespace GridGenerator
  {
    /**
     * Create a 2D/3D cylinder configuration with the given length and
     * height.
     *
     * We set Dirichlet boundary conditions on the left boundary and
     * do-nothing boundary conditions on the right boundary. All other
     * boundaries (including the cylinder) have slip boundary conditions
     * prescribed.
     *
     * The 3D mesh is created by extruding the 2D mesh with a width equal
     * to the "height".
     *
     * @ingroup Mesh
     */
    template <int dim, int spacedim, template <int, int> class Triangulation>
    void three_part_airfoil(Triangulation<dim, spacedim> &)
    {
      AssertThrow(false, dealii::ExcNotImplemented());
      __builtin_trap();
    }


#ifndef DOXYGEN
    template <template <int, int> class Triangulation>
    void three_part_airfoil(Triangulation<2, 2> &triangulation)
    {
      const double left_boundary_x_coordinate = -1000.;
      const double bottom_boundary_y_coordinate = -1000.;

      const double right_boundary_x_coordinate = 1000.;
      const double top_boundary_y_coordinate = 1000.;

      // Set boundary ids.
      for (auto cell : triangulation.active_cell_iterators()) {
        for (auto f : cell->face_indices()) {
          const auto face = cell->face(f);

          if (!face->at_boundary())
            continue;

          const auto center = face->center();
          // On the left and bottom parts of the domain, we want dirichlet
          // boundary conditions.
          if (std::abs(center[0] - left_boundary_x_coordinate) < 1e-10 ||
              std::abs(center[1] - bottom_boundary_y_coordinate) < 1e-10) {
            face->set_boundary_id(Boundary::dirichlet);
            continue;
          }

          // if on top or right, we do nothing
          if (std::abs(center[0] - right_boundary_x_coordinate) < 1e-10 ||
              std::abs(center[1] - top_boundary_y_coordinate) < 1e-10) {
            face->set_boundary_id(Boundary::do_nothing);
            continue;
          }

          // if neither of the above are true, we are on the three part airfoil,
          // and we should designate a slip/object boundary condition.
          face->set_boundary_id(Boundary::object);
        } // face loop
      }   // cell loop
    }

#endif
  } /* namespace GridGenerator */

  namespace Geometries
  {

    /**
     * A Special 3-part airfoil that requires the file wing.msh,
     * generated by MIT using an output-based mesh adaptation
     * algorithm to minimize numerical error in drag for the SA-neg
     * turbulence model at alpha=16 deg, and are not suitable for
     * any other angle of attack or turbulence model.
     *
     * The mesh, in tets can be found at
     * https://turbmodels.larc.nasa.gov/multielementverif_grids.html
     *
     * @ingroup Mesh
     */
    template <int dim>
    class ThreePartAirfoil : public Geometry<dim>
    {
    public:
      ThreePartAirfoil(const std::string subsection)
          : Geometry<dim>("three part airfoil", subsection)
      {
        // No parameters relevant, we don't change anything except for
        // refinements other than the airfoil name.
        airfoil_type_ = "mit_three_part_wing";
        file_location_ = "./wing.msh";
        this->add_parameter(
            "three part wing file location",
            file_location_,
            "The location in your system of the three part MIT wing .msh");
        mean_areodynamic_chord_ = 3.8; // MAC for 737 aircraft
        this->add_parameter(
            "mean areodynamic chord",
            mean_areodynamic_chord_,
            "The mean areodynamic chord is the average length of the "
            "airfoil. Setting this will scale the triangulation so that "
            "the airfoil is the length desired.");
      }

      void create_triangulation(
          typename Geometry<dim>::Triangulation &triangulation) final
      {
        dealii::GridIn grid_in(triangulation);
        std::ifstream stream(file_location_);
        grid_in.read_msh(stream);
        GridGenerator::three_part_airfoil(triangulation);

        // Scale the triangulation so that the MAC is correct.
        dealii::GridTools::scale(mean_areodynamic_chord_, triangulation);
      }

    private:
      std::string airfoil_type_;
      std::string file_location_;
      double mean_areodynamic_chord_;
    };
  } /* namespace Geometries */
} /* namespace ryujin */
